// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkuZfCQgafAransQqpxHoiuq-ojVGX4tQ',
    appId: '1:966825894678:web:a404b4fef75c0e9da92637',
    messagingSenderId: '966825894678',
    projectId: 'project-final-mobile',
    authDomain: 'project-final-mobile.firebaseapp.com',
    storageBucket: 'project-final-mobile.appspot.com',
    measurementId: 'G-WH1TNDDP3V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkP4MNkeos_cEQRl5NWbjyUQFUE1hxDgo',
    appId: '1:966825894678:android:fdc1e6528b0b733da92637',
    messagingSenderId: '966825894678',
    projectId: 'project-final-mobile',
    storageBucket: 'project-final-mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXZCJgXQCLKtEzD_DbT25nYbsKAaQXZuo',
    appId: '1:966825894678:ios:966287d29835ac9ba92637',
    messagingSenderId: '966825894678',
    projectId: 'project-final-mobile',
    storageBucket: 'project-final-mobile.appspot.com',
    iosClientId: '966825894678-p4ou7hc1u203a4fet0khmbfollto1fde.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProjectMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXZCJgXQCLKtEzD_DbT25nYbsKAaQXZuo',
    appId: '1:966825894678:ios:966287d29835ac9ba92637',
    messagingSenderId: '966825894678',
    projectId: 'project-final-mobile',
    storageBucket: 'project-final-mobile.appspot.com',
    iosClientId: '966825894678-p4ou7hc1u203a4fet0khmbfollto1fde.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProjectMobile',
  );
}
